# Generated by Django 4.1.5 on 2023-04-01 21:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import repository.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(default=repository.models.Project.set_id, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=115, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_page', models.ImageField(upload_to=repository.models.set_cover_upload)),
                ('document', models.FileField(upload_to=repository.models.set_document_upload, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('url', models.URLField(null=True)),
                ('supervisor', models.CharField(max_length=50)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('year_published', models.CharField(max_length=4, validators=[repository.models.year_validator])),
                ('views', models.PositiveIntegerField(default=0)),
                ('plagiarism_score', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='repository.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='account.institution')),
                ('scholar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='projects', to='repository.tag')),
            ],
        ),
    ]
