# Generated by Django 4.1.5 on 2023-01-24 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repository.models
from uuid import uuid4


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=130, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_page', models.ImageField(null=True, upload_to=repository.models.set_cover_upload)),
                ('document', models.FileField(upload_to=repository.models.set_document_upload)),
                ('url', models.URLField(null=True)),
                ('author', models.JSONField()),
                ('citation', models.TextField()),
                ('supervisor', models.CharField(max_length=50)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('year_published', models.CharField(max_length=4, validators=[repository.models.year_validator])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('projects', models.ManyToManyField(related_name='tags', to='repository.project')),
            ],
        ),
    ]
