# Generated by Django 4.1.5 on 2023-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='similarity_check_id',
            field=models.SlugField(default='ssssowk3332kdksd', unique=True),
            preserve_default=False,
        ),
    ]
