# Generated by Django 4.1.5 on 2023-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_project_similarity_check_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='similarity_check_id',
            field=models.SlugField(default=None, max_length=33, null=True),
        ),
    ]
