# Generated by Django 4.1.5 on 2023-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_remove_tag_projects_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
