# Generated by Django 4.1.5 on 2023-03-05 20:04

from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_page',
            field=models.ImageField(default=1, upload_to=repository.models.set_cover_upload),
            preserve_default=False,
        ),
    ]
