# Generated by Django 4.1.5 on 2023-03-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0007_alter_project_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scholar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
