# Generated by Django 4.1.5 on 2023-04-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_remove_project_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
