# Generated by Django 4.1.5 on 2023-04-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
