# Generated by Django 4.1.5 on 2023-03-08 21:55

import django.core.validators
from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_alter_project_scholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_page',
            field=models.ImageField(upload_to=repository.models.set_cover_upload, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(upload_to=repository.models.set_document_upload, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
