# Generated by Django 4.1.5 on 2023-03-08 22:08

from django.db import migrations, models
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_alter_project_cover_page_alter_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_page',
            field=models.ImageField(upload_to=repository.models.set_cover_upload),
        ),
    ]
