# Generated by Django 4.1.5 on 2023-02-22 14:20

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_email_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.set_name),
        ),
    ]
