# Generated by Django 4.1.5 on 2023-03-08 20:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_institution_account_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='profile-picture/avatar.png', upload_to=account.models.set_name),
        ),
    ]
